authorName: default
experimentName: Sparse-DPCML-ml-1m
trialConcurrency: 4
trainingServicePlatform: local
searchSpacePath: params.json
useAnnotation: false
tuner:
       builtinTunerName: GridSearch
# tuner:
#   builtinTunerName: TPE
#   classArgs:
#     optimize_mode: maximize
#     parallel_optimize: True
#     constant_liar_type: min
trial:
        command: python3 train_nni.py
        codeDir: .
        gpuNum: 1
assessor:
   #builtinAssessorName: Curvefitting
   #classArgs:
   #     epoch_num: 6
   #     start_step: 1
   #     threshold: 1.0
   #     gap: 1
  #builtinAssessorName: Medianstop
  #classArgs:
  #   optimize_mode: maximize
  #    start_step: 1
   codeDir: .
   classFileName: config_assessor.py
   className: CustomizedAssessor
   classArgs:
        # epoch_num: 5
        epoch_num: 100
        start_up: 1
        gap: 1
        higher_is_better: True
localConfig:
        useActiveGpu: true
        maxTrialNumPerGpu: 1
        gpuIndices: 4,5,6,7